### PR TITLE
Allow using user-specific credentials

### PR DESCRIPTION
**Pull request by eozturk1**
Updating the settings file to allow user-specific credentials using `$USER` and `$HOME` variables. Old credentials might need to be renamed/moved.

### CODE REVIEW

**Comment by eozturk1** [comment]
The key I generated on the AWS console loads fine but I seem to getting `botocore.exceptions.NoCredentialsError: Unable to locate credentials` errors. Any ideas what I might be missing?

**Comment by asonnino** [comment]
> The key I generated on the AWS console loads fine but I seem to getting `botocore.exceptions.NoCredentialsError: Unable to locate credentials` errors. Any ideas what I might be missing?

I think AWS doesn't expose APIs to upload ssh public keys, so we have to do it manually: https://docs.aws.amazon.com/ground-station/latest/ug/create-ec2-ssh-key-pair.html

Basically I went on every AWS region I plan to use and manually pasted my SSH public key in the UI.

**Comment by eozturk1** [comment]
I've pasted the key to all regions but I am still getting the same error. Does the merged change work fine on your machine after moving/renaming your key as expected in the settings?

**Comment by asonnino** [comment]
yes I just merged and managed to re-create a testbed from start (called `alberto-key-transparency`), everything seems to work fine until now.

**Comment by eozturk1** [comment]
I don't but I couldn't create one for myself. Could you help with that?

**Pull request merged**
